# Generated by Django 3.2.23 on 2023-11-20 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentlikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'ordering': ['-created_at']},
        ),
    ]
