# Generated by Django 3.2.23 on 2023-11-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='country',
            new_name='location',
        ),
        migrations.AddField(
            model_name='post',
            name='region',
            field=models.CharField(choices=[('Asia', 'Asia'), ('Africa', 'Africa'), ('North America', 'North America'), ('South America', 'South America'), ('Antarctica', 'Antarctica'), ('Europe', 'Europe'), ('Australien', 'Australien')], default='Europe', max_length=50),
        ),
    ]
