# Generated by Django 3.2.23 on 2023-11-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explorer',
            old_name='region',
            new_name='region_you_would_like_to_explore',
        ),
        migrations.AlterField(
            model_name='explorer',
            name='image',
            field=models.ImageField(default='../default_profile_aezplu', upload_to='images/'),
        ),
    ]
