# Generated by Django 3.2.23 on 2023-11-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0002_auto_20231106_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explorer',
            name='bio',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
